/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Alex human (https://sketchfab.com/alex-human)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/javascript-logo-3d-model-792093fab435419ab70dae39d2891cb3
Title: JavaScript Logo – 3D Model
*/

import { Float, useGLTF } from "@react-three/drei";

const JavascriptLogo = (props) => {
  const { nodes, materials } = useGLTF("models/javascript_logo__3d_model.glb");
  return (
    <Float floatIntensity={1}>
      <group position={[8, 8, 0]} scale={0.01} {...props} dispose={null}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.yellow} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.black} />
      </group>
    </Float>
  );
};

useGLTF.preload("models/javascript_logo__3d_model.glb");
export default JavascriptLogo;

// import { useGLTF } from "@react-three/drei";
// import { useRef } from "react";
// import type { JSX } from "react";
// import * as THREE from "three";
// import gsap from 'gsap';
// import { useGSAP } from "@gsap/react";

// const JavascriptLogo = (props: JSX.IntrinsicElements['mesh']) => {
//   const targetRef = useRef<THREE.Mesh>(null);
//   const { scene } = useGLTF('/models/javascript_logo__3d_model.glb');

//   useGSAP(() => {
//     if (!targetRef.current) return; // ✅ vérifie null

//     gsap.to(targetRef.current.position, {
//       y: targetRef.current.position.y + 0.5,
//       duration: 1.5,
//       repeat: -1,
//       yoyo: true,
//     });
//   });

//   return (
//     <mesh ref={targetRef} {...props}>
//       <primitive object={scene} />
//     </mesh>
//   );
// };

// // ✅ Un seul nom partout
// useGLTF.preload('/models/javascript_logo__3d_model.glb');
// export default JavascriptLogo;
